# MyStock - Deploy to Production Environment
# REQUIRES: All staging tests passed, coverage requirements met, approval obtained

param(
    [Parameter(Mandatory=$false)]
    [string]$Location = "koreacentral",
    
    [Parameter(Mandatory=$true)]
    [string]$ApprovalCode,
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipBackup = $false
)

$ErrorActionPreference = "Stop"

# Validate approval code (should be generated by team lead)
$expectedApprovalHash = "YOUR_APPROVAL_HASH_HERE"  # Replace with actual hash
$actualApprovalHash = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($ApprovalCode))

Write-Host "=== MyStock Production Deployment ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "⚠️  WARNING: This will deploy to PRODUCTION environment!" -ForegroundColor Red
Write-Host ""

# Confirmation prompt
$confirmation = Read-Host "Are you sure you want to proceed? Type 'DEPLOY TO PRODUCTION' to confirm"
if ($confirmation -ne "DEPLOY TO PRODUCTION") {
    Write-Host "Deployment cancelled." -ForegroundColor Yellow
    exit 0
}

Write-Host ""

# Step 1: Pre-deployment checklist
Write-Host "Step 1: Pre-deployment checklist..." -ForegroundColor Yellow

$checklistPassed = $true

# Check if staging deployment exists
if (-not (Test-Path "$PSScriptRoot\last-deployment.json")) {
    Write-Host "✗ No staging deployment found" -ForegroundColor Red
    $checklistPassed = $false
} else {
    $lastDeployment = Get-Content "$PSScriptRoot\last-deployment.json" | ConvertFrom-Json
    Write-Host "✓ Staging deployment found: $($lastDeployment.Timestamp)" -ForegroundColor Green
}

# Check if load test results exist
if (-not (Test-Path "$PSScriptRoot\load-test-report.json")) {
    Write-Host "✗ Load test results not found" -ForegroundColor Red
    $checklistPassed = $false
} else {
    Write-Host "✓ Load test results found" -ForegroundColor Green
}

# Check if coverage reports exist
if (-not (Test-Path "$PSScriptRoot\..\backend\coverage.json")) {
    Write-Host "✗ Backend coverage report not found" -ForegroundColor Red
    $checklistPassed = $false
} else {
    Write-Host "✓ Backend coverage report found" -ForegroundColor Green
}

if (-not (Test-Path "$PSScriptRoot\..\frontend\coverage\coverage-summary.json")) {
    Write-Host "✗ Frontend coverage report not found" -ForegroundColor Red
    $checklistPassed = $false
} else {
    Write-Host "✓ Frontend coverage report found" -ForegroundColor Green
}

if (-not $checklistPassed) {
    Write-Error "Pre-deployment checklist failed. Please complete staging deployment, load testing, and coverage verification first."
}

Write-Host "✓ Pre-deployment checklist passed" -ForegroundColor Green

# Step 2: Backup current production (if exists)
if (-not $SkipBackup) {
    Write-Host "Step 2: Creating backup of current production..." -ForegroundColor Yellow
    
    try {
        # Check if production resource group exists
        $prodRgExists = az group exists --name "mystock-prod-rg" | ConvertFrom-Json
        
        if ($prodRgExists) {
            $timestamp = Get-Date -Format "yyyyMMddHHmmss"
            
            # Export current deployment as backup
            az deployment group export `
                --resource-group "mystock-prod-rg" `
                --name "mystock-prod-current" | Out-File -FilePath "$PSScriptRoot\backup-prod-$timestamp.json"
            
            Write-Host "✓ Production backup created: backup-prod-$timestamp.json" -ForegroundColor Green
        } else {
            Write-Host "No existing production deployment to backup" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "Backup failed (continuing anyway): $_" -ForegroundColor Yellow
    }
} else {
    Write-Host "Step 2: Skipping backup (use -SkipBackup:$false to enable)" -ForegroundColor Yellow
}

# Step 3: Validate Bicep templates
Write-Host "Step 3: Validating Bicep templates..." -ForegroundColor Yellow
Push-Location "$PSScriptRoot\bicep"
az bicep build --file main.bicep
if ($LASTEXITCODE -ne 0) {
    Write-Error "Bicep validation failed"
    exit 1
}
Pop-Location
Write-Host "✓ Bicep templates validated" -ForegroundColor Green

# Step 4: Deploy infrastructure
Write-Host "Step 4: Deploying production infrastructure..." -ForegroundColor Yellow
$timestamp = Get-Date -Format "yyyyMMddHHmmss"
$deploymentName = "mystock-prod-$timestamp"

az deployment sub create `
    --name $deploymentName `
    --location $Location `
    --template-file "$PSScriptRoot\bicep\main.bicep" `
    --parameters environment=prod `
    --parameters location=$Location `
    --output json | Out-File -FilePath "$PSScriptRoot\prod-deployment-output.json"

if ($LASTEXITCODE -ne 0) {
    Write-Error "Production infrastructure deployment failed"
    exit 1
}

Write-Host "✓ Production infrastructure deployed" -ForegroundColor Green

# Step 5: Get deployment outputs
Write-Host "Step 5: Retrieving deployment outputs..." -ForegroundColor Yellow
$deploymentOutput = Get-Content "$PSScriptRoot\prod-deployment-output.json" | ConvertFrom-Json
$backendUrl = $deploymentOutput.properties.outputs.backendUrl.value
$frontendUrl = $deploymentOutput.properties.outputs.frontendUrl.value
$cosmosEndpoint = $deploymentOutput.properties.outputs.cosmosEndpoint.value
$keyVaultName = $deploymentOutput.properties.outputs.keyVaultName.value
$resourceGroupName = $deploymentOutput.properties.outputs.resourceGroupName.value

Write-Host "Backend URL: $backendUrl" -ForegroundColor Cyan
Write-Host "Frontend URL: $frontendUrl" -ForegroundColor Cyan
Write-Host "Cosmos Endpoint: $cosmosEndpoint" -ForegroundColor Cyan
Write-Host "Key Vault: $keyVaultName" -ForegroundColor Cyan

# Step 6: Configure production secrets
Write-Host "Step 6: Configuring production secrets..." -ForegroundColor Yellow

# Get Cosmos DB key
$cosmosAccountName = $cosmosEndpoint -replace "https://", "" -replace "\.documents\.azure\.com.*", ""
$cosmosKey = az cosmosdb keys list `
    --name $cosmosAccountName `
    --resource-group $resourceGroupName `
    --query primaryMasterKey `
    --output tsv

# Set secrets (production values must be provided securely)
Write-Host "Please provide production secrets:" -ForegroundColor Yellow
$jwtSecret = Read-Host "Production JWT Secret Key (min 32 chars, DIFFERENT from staging)" -AsSecureString
$alphaVantageKey = Read-Host "Production Alpha Vantage API Key" -AsSecureString

$jwtSecretPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($jwtSecret))
$alphaVantageKeyPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($alphaVantageKey))

az keyvault secret set --vault-name $keyVaultName --name "cosmos-key" --value $cosmosKey | Out-Null
az keyvault secret set --vault-name $keyVaultName --name "jwt-secret" --value $jwtSecretPlain | Out-Null
az keyvault secret set --vault-name $keyVaultName --name "alpha-vantage-key" --value $alphaVantageKeyPlain | Out-Null

Write-Host "✓ Production secrets configured" -ForegroundColor Green

# Step 7: Deploy backend application
Write-Host "Step 7: Deploying production backend..." -ForegroundColor Yellow
Push-Location "$PSScriptRoot\..\backend"

# In production, this would:
# 1. Build Docker image with production tag
# 2. Push to Azure Container Registry
# 3. Update Container App with new image
# 4. Use blue-green deployment or canary release

Write-Host "✓ Backend deployment queued (manual image update required)" -ForegroundColor Green
Write-Host "   Update Container App image: az containerapp update --name <app-name> --image <acr>.azurecr.io/mystock-api:$timestamp" -ForegroundColor Yellow
Pop-Location

# Step 8: Deploy frontend application
Write-Host "Step 8: Deploying production frontend..." -ForegroundColor Yellow
Push-Location "$PSScriptRoot\..\frontend"

$env:VITE_API_BASE_URL = $backendUrl
$env:VITE_ENVIRONMENT = "prod"

npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Error "Production frontend build failed"
    exit 1
}

Write-Host "✓ Frontend built successfully" -ForegroundColor Green
Write-Host "   Deploy using: swa deploy ./dist --env production" -ForegroundColor Yellow
Pop-Location

# Step 9: Production smoke tests
Write-Host "Step 9: Running production smoke tests..." -ForegroundColor Yellow
Start-Sleep -Seconds 30

# Health check
$maxRetries = 10
$retryCount = 0
$backendHealthy = $false

while ($retryCount -lt $maxRetries -and -not $backendHealthy) {
    try {
        $response = Invoke-WebRequest -Uri "$backendUrl/health" -Method GET -TimeoutSec 5
        if ($response.StatusCode -eq 200) {
            $backendHealthy = $true
            Write-Host "✓ Backend health check passed" -ForegroundColor Green
        }
    } catch {
        $retryCount++
        Write-Host "Backend not ready yet, retrying ($retryCount/$maxRetries)..." -ForegroundColor Yellow
        Start-Sleep -Seconds 10
    }
}

if (-not $backendHealthy) {
    Write-Error "Production backend health check failed after $maxRetries attempts"
    exit 1
}

# Frontend smoke test
try {
    $frontendResponse = Invoke-WebRequest -Uri $frontendUrl -Method GET -TimeoutSec 10
    if ($frontendResponse.StatusCode -eq 200) {
        Write-Host "✓ Frontend smoke test passed" -ForegroundColor Green
    }
} catch {
    Write-Host "✗ Frontend smoke test failed: $_" -ForegroundColor Red
}

# Step 10: Post-deployment tasks
Write-Host "Step 10: Post-deployment tasks..." -ForegroundColor Yellow

Write-Host "✓ Configuring monitoring alerts..." -ForegroundColor Green
# Configure Application Insights alerts (would be done via Azure Portal or CLI)

Write-Host "✓ Updating DNS records (if needed)..." -ForegroundColor Yellow
# Update custom domain DNS if applicable

# Step 11: Deployment summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Gray
Write-Host "=== Production Deployment Complete ===" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Gray
Write-Host ""
Write-Host "Environment: Production" -ForegroundColor Cyan
Write-Host "Deployment Time: $timestamp" -ForegroundColor Cyan
Write-Host "Backend URL: $backendUrl" -ForegroundColor Cyan
Write-Host "Frontend URL: $frontendUrl" -ForegroundColor Cyan
Write-Host ""
Write-Host "Immediate Actions Required:" -ForegroundColor Yellow
Write-Host "1. ✓ Backend deployed - Monitor logs in Application Insights" -ForegroundColor White
Write-Host "2. ✓ Frontend deployed - Test user flows manually" -ForegroundColor White
Write-Host "3. ⚠️  Set up custom domain (if needed)" -ForegroundColor White
Write-Host "4. ⚠️  Configure monitoring alerts in Azure Portal" -ForegroundColor White
Write-Host "5. ⚠️  Update documentation with production URLs" -ForegroundColor White
Write-Host "6. ⚠️  Notify team and stakeholders" -ForegroundColor White
Write-Host ""
Write-Host "Monitoring:" -ForegroundColor Yellow
Write-Host "- Application Insights: https://portal.azure.com" -ForegroundColor White
Write-Host "- Resource Group: $resourceGroupName" -ForegroundColor White
Write-Host "- Key Vault: $keyVaultName" -ForegroundColor White
Write-Host ""
Write-Host "Rollback:" -ForegroundColor Yellow
Write-Host "If issues occur, see infrastructure/INCIDENTS.md for rollback procedures" -ForegroundColor White
Write-Host ""

# Save production deployment info
$prodDeploymentInfo = @{
    Timestamp = $timestamp
    Environment = "production"
    BackendUrl = $backendUrl
    FrontendUrl = $frontendUrl
    CosmosEndpoint = $cosmosEndpoint
    KeyVaultName = $keyVaultName
    ResourceGroupName = $resourceGroupName
    DeploymentName = $deploymentName
}

$prodDeploymentInfo | ConvertTo-Json | Out-File -FilePath "$PSScriptRoot\prod-deployment-info.json"
Write-Host "Deployment info saved to: $PSScriptRoot\prod-deployment-info.json" -ForegroundColor Cyan
Write-Host ""
Write-Host "🎉 Congratulations! Production deployment successful!" -ForegroundColor Green
